# Generated by Django 6.0.5 on 2026-05-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('materiales', 'Materiales académicos'), ('fotocopias', 'Fotocopias'), ('entretenimiento', 'Entretenimiento'), ('salud', 'Salud'), ('servicios', 'Servicios'), ('mesada', 'Mesada'), ('trabajo', 'Trabajo'), ('beca', 'Beca'), ('otro', 'Otro')], max_length=20, verbose_name='categoría')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='presupuesto')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='color')),
            ],
            options={
                'verbose_name': 'Presupuesto de Categoría',
                'verbose_name_plural': 'Presupuestos de Categorías',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto objetivo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='progreso actual')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('is_completed', models.BooleanField(default=False, verbose_name='completada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'Meta de Ahorro',
                'verbose_name_plural': 'Metas de Ahorro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10, verbose_name='tipo de transacción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('category', models.CharField(choices=[('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('materiales', 'Materiales académicos'), ('fotocopias', 'Fotocopias'), ('entretenimiento', 'Entretenimiento'), ('salud', 'Salud'), ('servicios', 'Servicios'), ('mesada', 'Mesada'), ('trabajo', 'Trabajo'), ('beca', 'Beca'), ('otro', 'Otro')], max_length=20, verbose_name='categoría')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('date', models.DateField(verbose_name='fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
