# Generated by Django 6.0.5 on 2026-05-20 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('category', models.CharField(choices=[('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('materiales', 'Materiales académicos'), ('fotocopias', 'Fotocopias'), ('entretenimiento', 'Entretenimiento'), ('salud', 'Salud'), ('servicios', 'Servicios'), ('mesada', 'Mesada'), ('trabajo', 'Trabajo'), ('beca', 'Beca'), ('otro', 'Otro')], default='entretenimiento', max_length=20, verbose_name='categoría')),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=10, verbose_name='frecuencia')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='próxima fecha de cobro')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['next_billing_date'],
            },
        ),
    ]
