# Generated by Django 6.0.5 on 2026-05-20 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre del crédito')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto total prestado')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='saldo pendiente')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor de la cuota')),
                ('total_installments', models.IntegerField(verbose_name='cuotas totales')),
                ('paid_installments', models.IntegerField(default=0, verbose_name='cuotas pagadas')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='tasa de interés mensual (%)')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('next_payment_date', models.DateField(blank=True, null=True, verbose_name='próxima fecha de pago')),
                ('category', models.CharField(choices=[('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('materiales', 'Materiales académicos'), ('fotocopias', 'Fotocopias'), ('entretenimiento', 'Entretenimiento'), ('salud', 'Salud'), ('servicios', 'Servicios'), ('mesada', 'Mesada'), ('trabajo', 'Trabajo'), ('beca', 'Beca'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['next_payment_date'],
            },
        ),
    ]
