# Generated by Django 6.0.5 on 2026-05-15 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('difficulty', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='facil', max_length=10, verbose_name='dificultad')),
                ('reward_points', models.PositiveIntegerField(default=10, verbose_name='puntos de recompensa')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'Reto Educativo',
                'verbose_name_plural': 'Retos Educativos',
                'ordering': ['difficulty', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('category', models.CharField(max_length=50, verbose_name='categoría')),
                ('read_time', models.CharField(max_length=20, verbose_name='tiempo de lectura')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='color')),
                ('content', models.TextField(blank=True, verbose_name='contenido')),
            ],
            options={
                'verbose_name': 'Guía Educativa',
                'verbose_name_plural': 'Guías Educativas',
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('pending', 'Pendiente'), ('completed', 'Completado')], default='pending', max_length=15, verbose_name='estado')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='progreso')),
                ('total', models.PositiveIntegerField(default=1, verbose_name='total a completar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='education.challenge')),
            ],
            options={
                'verbose_name': 'Progreso de Reto',
                'verbose_name_plural': 'Progresos de Retos',
            },
        ),
    ]
