# Generated by Django 6.0.5 on 2026-05-20 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_question_choice_quiz_question_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['difficulty', '-created_at'], 'verbose_name': 'Reto / Misión', 'verbose_name_plural': 'Retos / Misiones'},
        ),
        migrations.AddField(
            model_name='challenge',
            name='trigger_total',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de veces que debe cumplirse el trigger.', verbose_name='total requerido'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='trigger_type',
            field=models.CharField(choices=[('register_transactions', 'Registrar N transacciones (total)'), ('daily_transaction', 'Registrar una transacción hoy'), ('set_budget', 'Configurar presupuesto en N categorías'), ('create_goal', 'Crear N metas de ahorro'), ('fund_goal', 'Aportar a una meta de ahorro'), ('complete_quiz', 'Completar un quiz'), ('read_guide', 'Leer una guía educativa'), ('savings_rate_10', 'Lograr tasa de ahorro >= 10% este mes'), ('savings_rate_20', 'Lograr tasa de ahorro >= 20% este mes'), ('no_small_expenses_7', 'No tener gastos de entretenimiento por 7 días'), ('emergency_fund_100k', 'Tener meta con >= $100.000 aportados'), ('add_subscription', 'Registrar una suscripción recurrente'), ('streak_3', 'Mantener racha de 3 días'), ('streak_7', 'Mantener racha de 7 días'), ('manual', 'Completar manualmente')], default='manual', max_length=30, verbose_name='tipo de trigger'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de completado'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('pending', 'Pendiente'), ('completed', 'Completado')], default='active', max_length=15, verbose_name='estado'),
        ),
        migrations.CreateModel(
            name='UserGuideRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de lectura')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='education.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guía Leída',
                'verbose_name_plural': 'Guías Leídas',
                'unique_together': {('user', 'guide')},
            },
        ),
    ]
