# Generated by Django 6.0.5 on 2026-05-15 17:58

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Debe ser un correo institucional (.edu)', max_length=254, unique=True, validators=[users.models.validate_edu_email], verbose_name='correo electrónico')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='apellidos')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='universidad')),
                ('career', models.CharField(blank=True, max_length=200, verbose_name='carrera')),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='semestre')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='racha de días')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='puntos')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('warning', 'Advertencia'), ('info', 'Información'), ('success', 'Éxito'), ('error', 'Error')], default='info', max_length=10, verbose_name='tipo')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('is_read', models.BooleanField(default=False, verbose_name='leída')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income_level', models.CharField(choices=[('bajo', 'Menos de $500.000'), ('medio', '$500.000 - $1.500.000'), ('alto', 'Más de $1.500.000')], max_length=10, verbose_name='nivel de ingresos mensual')),
                ('financial_knowledge', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15, verbose_name='nivel de conocimiento financiero')),
                ('main_financial_goal', models.CharField(choices=[('ahorrar', 'Aprender a ahorrar'), ('deudas', 'Salir de deudas'), ('presupuesto', 'Controlar mi presupuesto'), ('invertir', 'Empezar a invertir')], max_length=15, verbose_name='objetivo financiero principal')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de completado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Onboarding',
                'verbose_name_plural': 'Perfiles de Onboarding',
            },
        ),
    ]
