# Generated by Django 6.0.5 on 2026-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
            },
        ),
    ]
