# Generated by Django 6.0.5 on 2026-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='biografía'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('universidad', 'Universidad'), ('instituto', 'Instituto Técnico/Tecnológico'), ('colegio', 'Colegio / Escuela'), ('otro', 'Otro')], max_length=20, verbose_name='tipo de institución'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='teléfono'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='study_work_status',
            field=models.CharField(blank=True, choices=[('solo_estudia', 'Solo Estudia'), ('estudia_trabaja', 'Estudia y Trabaja'), ('solo_trabaja', 'Solo Trabaja'), ('buscando_empleo', 'Buscando Empleo'), ('otro', 'Otro')], max_length=25, verbose_name='estado académico/laboral'),
        ),
    ]
